name: Train_Carts
version: '${version}'
build: '${build}'
dev-url: https://github.com/bergerhealer/TrainCarts
description: Plugin that allows the use of minecart trains with adjustable settings
authors: [bergerkiller, lenis0012, timstans, bubba1234119, KamikazePlatypus, mg_1999, Friwi, kpaulisse]
api-version: 1.13
softdepend: [BKCommonLib, MinecartManiaCore, SignLink, My_Worlds, LightAPI, Vault, WorldEdit]
classdepend: [TAB]

bstats:
    enabled: true
    plugin-id: 18761

main: com.bergerkiller.bukkit.tc.Preloader
preloader:
    main: com.bergerkiller.bukkit.tc.TrainCarts
    hastebinServer: https://paste.traincarts.net
    commands: [train, cart, savedtrain]
    depend:
        BKCommonLib: https://www.spigotmc.org/resources/bkcommonlib.39590/
