name: Train Carts
main: com.bergerkiller.bukkit.tc.TrainCarts
version: 1.33
author: bergerkiller
description: Plugin that allows the use of minecart trains with adjustable settings
softdepend: [MinecartManiaCore, SignLink, My Worlds]
permissions:
    train.build.station:
        description: Allows you to build station signs
        default: op
    train.build.spawner:
        description: Allows you to build the train spawner signs
        default: op
    train.build.trigger:
        description: Allows you to build trigger signs (arrival times)
        default: op
    train.build.destructor:
        description: Allows you to build destructor signs
        default: op
    train.build.ejector:
        description: Allows you to build ejector signs
        default: op
    train.build.pushHandler:
        description: Allows you to build push handler signs to stop or allow a train to be pushed
        default: op
    train.place.minecart:
        description: Allows you to place a minecart
        default: true